name: data_cache_manger
description: useful package to manage data caching
version: 0.0.1
homepage: https://github.com/mjdarvishi/data_cache_manger

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

